Output demo.gif

Set Width 1150
Set Height 700
Set FontSize 18
Env PROMPT ">"

Type "greyscale show info --infile ~/8bitgreyscale.png"
Enter

Sleep 2s

Hide
Type "clear"
Enter
Show

Type "greyscale show colors --infile ~/8bitgreyscale.png"
Enter

Sleep 2s

Hide
Type "clear"
Enter
Show

Enter
Type "greyscale show colors --infile ~/8bitgreyscale.png --pixels 0,153:300 --top 2"
Enter

Sleep 2s

Hide
Type "clear"
Enter
Show
